name: id_doc_kit
description: >
  Indian ID validation helpers for KYC and onboarding (Aadhaar, PAN, GSTIN, DL, Voter ID, Passport + PIN/Phone/Email).

version: 0.0.9

homepage: https://github.com/jagadeeshpodilapu/id_doc_kit
repository: https://github.com/jagadeeshpodilapu/id_doc_kit
issue_tracker: https://github.com/jagadeeshpodilapu/id_doc_kit/issues

topics:
  - india
  - kyc
  - aadhaar
  - pan
  - gstin

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
